// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyCNOcEOG9hEVOZlzsuwt1ocbPCXD6rL4',
    appId: '1:1068809628706:web:14958314ede98437a3ae7b',
    messagingSenderId: '1068809628706',
    projectId: 'flutterchatapp01-74b98',
    authDomain: 'flutterchatapp01-74b98.firebaseapp.com',
    storageBucket: 'flutterchatapp01-74b98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwKpQb-EjcD4_9qVxn35hwSbhBFHsumkQ',
    appId: '1:1068809628706:android:1d4affe83f948d1fa3ae7b',
    messagingSenderId: '1068809628706',
    projectId: 'flutterchatapp01-74b98',
    storageBucket: 'flutterchatapp01-74b98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbNvFToEmBvQ3L2dfopFixNpSdcqR2ATk',
    appId: '1:1068809628706:ios:d619829731e41380a3ae7b',
    messagingSenderId: '1068809628706',
    projectId: 'flutterchatapp01-74b98',
    storageBucket: 'flutterchatapp01-74b98.appspot.com',
    iosBundleId: 'com.example.flutterchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbNvFToEmBvQ3L2dfopFixNpSdcqR2ATk',
    appId: '1:1068809628706:ios:b1811d6b0ea8768aa3ae7b',
    messagingSenderId: '1068809628706',
    projectId: 'flutterchatapp01-74b98',
    storageBucket: 'flutterchatapp01-74b98.appspot.com',
    iosBundleId: 'com.example.flutterchatapp.RunnerTests',
  );
}
